/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:8918ee86-d558-46bb-be70-4cfe52eeae66",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_pk1wCcVOQ",
    "aws_user_pools_web_client_id": "1e2h7couqa5ogfdb2ilndsqb05",
    "oauth": {}
};


export default awsmobile;
