/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:538f7003-f561-417e-a3e0-fc98cbb0702c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_ZZkLMZ3jJ",
    "aws_user_pools_web_client_id": "46ueuo2hoj5bmlrtb1g1pdtbse",
    "oauth": {
        "domain": "tuduf71a77ac-f71a77ac-master.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://tudu.michaelkeller.dev/,https://tudu.kellermichael.com/,http://localhost:19006/",
        "redirectSignOut": "https://tudu.michaelkeller.dev/,https://tudu.kellermichael.com/,http://localhost:19006/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
